apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  type: LoadBalancer
  ports:
    - name: "8504"
      port: 8504
      targetPort: 8504
  selector:
    io.kompose.service: api
