apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bot
  name: bot
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
  selector:
    io.kompose.service: bot
