apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
    - name: "7687"
      port: 7687
      targetPort: 7687
    - name: "7474"
      port: 7474
      targetPort: 7474
  selector:
    io.kompose.service: database
