apiVersion: v1
kind: Service
metadata:
  name: database-loadbalancer
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: database
  ports:
    - protocol: TCP
      port: 7474
      targetPort: 7474