apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/password
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_db_tx__log_rotation_retention__policy
              value: "false"
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: apoc.*
          image: neo4j:5.11
          livenessProbe:
            exec:
              command:
                - wget --no-verbose --tries=1 --spider localhost:7474 || exit 1
            failureThreshold: 10
            periodSeconds: 15
            timeoutSeconds: 30
          name: database
          ports:
            - containerPort: 7687
              protocol: TCP
            - containerPort: 7474
              protocol: TCP
      restartPolicy: Always
