apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-end
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: front-end
    spec:
      containers:
        - image: andrewelizondo/genai-stack-front-end
          name: front-end
          ports:
            - containerPort: 8505
              protocol: TCP
      restartPolicy: Always
