apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  ports:
    - name: "8505"
      port: 8505
      targetPort: 8505
  selector:
    io.kompose.service: front-end
