apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: loader
  name: loader
spec:
  type: LoadBalancer
  ports:
    # - name: "8081"
    #   port: 8081
    #   targetPort: 8080
    - port: 8502
      targetPort: 8502
      protocol: TCP
  selector:
    io.kompose.service: loader
