apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: pdf-bot
  name: pdf-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pdf-bot
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: pdf-bot
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_DEFAULT_REGION
            - name: AWS_SECRET_ACCESS_KEY
            - name: EMBEDDING_MODEL
              value: sentence_transformer
            - name: GOOGLE_API_KEY
            - name: LANGCHAIN_API_KEY
            - name: LANGCHAIN_ENDPOINT
              value: '"https://api.smith.langchain.com"'
            - name: LANGCHAIN_PROJECT
            - name: LANGCHAIN_TRACING_V2
              value: "false"
            - name: LLM
              value: {{ .Values.llmName }}
            - name: NEO4J_PASSWORD
              value: password
            - name: NEO4J_URI
              value: neo4j://database:7687
            - name: NEO4J_USERNAME
              value: neo4j
            - name: OLLAMA_BASE_URL
              value: http://{{ template "ollama.fullname" .Subcharts.ollama }}:11434
            - name: OPENAI_API_KEY
          image: andrewelizondo/genai-stack-pdf_bot
          name: pdf-bot
          ports:
            - containerPort: 8503
              protocol: TCP
      restartPolicy: Always
