apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c --build local -v --profile linux
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: pdf-bot
  name: pdf-bot
spec:
  ports:
    - name: "8503"
      port: 8503
      targetPort: 8503
  selector:
    io.kompose.service: pdf-bot
